/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppConfiguracionRouteImport } from './routes/app/configuracion'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as AppEstablecimientosIndexRouteImport } from './routes/app/establecimientos/index'
import { Route as AppEstablecimientosEstablishmentIdRouteImport } from './routes/app/establecimientos/$establishmentId'
import { Route as AppExtintoresExtinguisherIdRouteImport } from './routes/app/extintores/$extinguisherId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEstablecimientosIndexRoute =
  AppEstablecimientosIndexRouteImport.update({
    id: '/establecimientos/',
    path: '/establecimientos/',
    getParentRoute: () => AppRoute,
  } as any)
const AppEstablecimientosEstablishmentIdRoute =
  AppEstablecimientosEstablishmentIdRouteImport.update({
    id: '/establecimientos/$establishmentId',
    path: '/establecimientos/$establishmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppExtintoresExtinguisherIdRoute =
  AppExtintoresExtinguisherIdRouteImport.update({
    id: '/extintores/$extinguisherId',
    path: '/extintores/$extinguisherId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/api/$': typeof ApiSplatRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/establecimientos/$establishmentId': typeof AppEstablecimientosEstablishmentIdRoute
  '/app/extintores/$extinguisherId': typeof AppExtintoresExtinguisherIdRoute
  '/app/establecimientos/': typeof AppEstablecimientosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/api/$': typeof ApiSplatRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/establecimientos/$establishmentId': typeof AppEstablecimientosEstablishmentIdRoute
  '/app/extintores/$extinguisherId': typeof AppExtintoresExtinguisherIdRoute
  '/app/establecimientos': typeof AppEstablecimientosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/api/$': typeof ApiSplatRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/establecimientos/$establishmentId': typeof AppEstablecimientosEstablishmentIdRoute
  '/app/extintores/$extinguisherId': typeof AppExtintoresExtinguisherIdRoute
  '/app/establecimientos/': typeof AppEstablecimientosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/iniciar-sesion'
    | '/registro'
    | '/api/$'
    | '/app/configuracion'
    | '/app/onboarding'
    | '/app/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/app/establecimientos/$establishmentId'
    | '/app/extintores/$extinguisherId'
    | '/app/establecimientos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iniciar-sesion'
    | '/registro'
    | '/api/$'
    | '/app/configuracion'
    | '/app/onboarding'
    | '/app'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/app/establecimientos/$establishmentId'
    | '/app/extintores/$extinguisherId'
    | '/app/establecimientos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/iniciar-sesion'
    | '/registro'
    | '/api/$'
    | '/app/configuracion'
    | '/app/onboarding'
    | '/app/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/app/establecimientos/$establishmentId'
    | '/app/extintores/$extinguisherId'
    | '/app/establecimientos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  IniciarSesionRoute: typeof IniciarSesionRoute
  RegistroRoute: typeof RegistroRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracion': {
      id: '/app/configuracion'
      path: '/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/establecimientos/': {
      id: '/app/establecimientos/'
      path: '/establecimientos'
      fullPath: '/app/establecimientos/'
      preLoaderRoute: typeof AppEstablecimientosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/establecimientos/$establishmentId': {
      id: '/app/establecimientos/$establishmentId'
      path: '/establecimientos/$establishmentId'
      fullPath: '/app/establecimientos/$establishmentId'
      preLoaderRoute: typeof AppEstablecimientosEstablishmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/extintores/$extinguisherId': {
      id: '/app/extintores/$extinguisherId'
      path: '/extintores/$extinguisherId'
      fullPath: '/app/extintores/$extinguisherId'
      preLoaderRoute: typeof AppExtintoresExtinguisherIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEstablecimientosEstablishmentIdRoute: typeof AppEstablecimientosEstablishmentIdRoute
  AppExtintoresExtinguisherIdRoute: typeof AppExtintoresExtinguisherIdRoute
  AppEstablecimientosIndexRoute: typeof AppEstablecimientosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
  AppEstablecimientosEstablishmentIdRoute:
    AppEstablecimientosEstablishmentIdRoute,
  AppExtintoresExtinguisherIdRoute: AppExtintoresExtinguisherIdRoute,
  AppEstablecimientosIndexRoute: AppEstablecimientosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  IniciarSesionRoute: IniciarSesionRoute,
  RegistroRoute: RegistroRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
